apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: file
  namespace: argo
spec:
  template:
    serviceAccountName: argo
  dependencies:
    - name: predict-dep
      eventSourceName: file
      eventName: predict
    - name: train-dep
      eventSourceName: file
      eventName: train
  triggers:
    - template:
        conditions: "predict-dep"
        name: predict-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: predict-watcher-
              spec:
                entrypoint: predict
                templates:
                - name: predict
                  container:
                    image: dimitrislask/isbp:predict
                    imagePullPolicy: Always
                    command: ["python", "predict.py"]
                    volumeMounts:
                    - name: shared-test
                      mountPath: /shared/
                  volumes:
                    - name: shared-test
                      persistentVolumeClaim:
                        claimName: isbp-persistent
    - template:
        conditions: "train-dep"
        name: train-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: train-watcher-
              spec:
                entrypoint: train
                templates:
                - name: train
                  container:
                    image: dimitrislask/isbp:train
                    imagePullPolicy: Always
                    command: ["python", "train.py"]
                    volumeMounts:
                    - name: shared-test
                      mountPath: /shared/
                  volumes:
                    - name: shared-test
                      persistentVolumeClaim:
                        claimName: isbp-persistent