kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: isbp
provisioner: kubernetes.io/no-provisioner

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: isbp-volume
  labels:
     vol: isbp-vol
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: isbp
  hostPath:
    path: /data/

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: isbp-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: isbp
  selector:
    matchLabels:
      vol: "isbp-vol"
